# Generated by Django 5.2.4 on 2025-07-22 19:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('clave_cliente', models.CharField(help_text='Clave de cliente de Aspel SAE', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SistemaAspel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sistema Aspel',
                'verbose_name_plural': 'Sistemas Aspel',
            },
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_licencia', models.CharField(help_text='Número de serie o código de activación de la licencia', max_length=255, unique=True)),
                ('version_software', models.CharField(blank=True, max_length=50, null=True)),
                ('reinstalable', models.CharField(blank=True, help_text='Número de versión menor del sistema Aspel del cliente (ej. 9.1, 10.3)', max_length=50, null=True)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('fecha_inicio_vigencia', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin_vigencia', models.DateField(blank=True, help_text='Fecha de vencimiento de la licencia (si aplica)', null=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida'), ('PENDIENTE_RENOVACION', 'Pendiente de Renovación'), ('INACTIVA', 'Inactiva')], default='ACTIVA', max_length=20)),
                ('tipo_licencia', models.CharField(choices=[('FISICA', 'Física'), ('ELECTRONICA', 'Electrónica'), ('SUSCRIPCION', 'Suscripción')], default='FISICA', help_text='Tipo de licencia (Física, Electrónica, Suscripción)', max_length=20)),
                ('periodo_licencia', models.CharField(blank=True, choices=[('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual'), ('PERPETUA', 'Perpetua')], help_text='Periodo de la licencia (Mensual, Anual, Perpetua, etc.)', max_length=20, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('numero_usuarios', models.IntegerField(default=1, help_text='Número de usuarios permitidos por la licencia')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to='licensing_management.cliente')),
                ('tipo_sistema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='licensing_management.sistemaaspel')),
            ],
            options={
                'verbose_name': 'Licencia',
                'verbose_name_plural': 'Licencias',
                'ordering': ['fecha_fin_vigencia', 'cliente'],
            },
        ),
    ]
