# Generated by Django 5.2.4 on 2025-07-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
