# Generated by Django 5.2.4 on 2025-07-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing_management', '0002_alter_cliente_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licencia',
            name='reinstalable',
        ),
        migrations.AddField(
            model_name='licencia',
            name='version_sistema',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Versión del Sistema'),
        ),
    ]
