# Generated by Django 5.2.4 on 2025-07-23 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing_management', '0003_remove_licencia_reinstalable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Sistema',
                'verbose_name_plural': 'Sistemas',
            },
        ),
        migrations.AlterField(
            model_name='licencia',
            name='tipo_sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='licensing_management.sistema'),
        ),
        migrations.DeleteModel(
            name='SistemaAspel',
        ),
    ]
