# Generated by Django 5.2.4 on 2025-07-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing_management', '0004_sistema_alter_licencia_tipo_sistema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema',
            name='categoria',
            field=models.CharField(choices=[('ASPEL', 'Aspel'), ('MICROSOFT_OFFICE_365', 'Microsoft Office 365'), ('ANTIVIRUS', 'Antivirus'), ('OTROS', 'Otros')], default='OTROS', max_length=50, verbose_name='Categoría del Sistema'),
        ),
    ]
