# Generated by Django 5.2.4 on 2025-07-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing_management', '0005_alter_sistema_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencia',
            name='tipo_licencia',
            field=models.CharField(choices=[('FISICA', 'Física'), ('ELECTRONICA', 'Electrónica'), ('SUSCRIPCION', 'Suscripción')], default='SUSCRIPCION', help_text='Tipo de licencia (Física, Electrónica, Suscripción)', max_length=20),
        ),
    ]
